apis:
  asyncapi:
    name: AsyncAPI
    icon: webhook
    description: Specification for building asynchronous APIs.
  openapi:
    name: OpenAPI
    icon: webhook
    description: Specification for building APIs.
  graphql:
    name: GraphQL
    icon: webhook
    description: Specification for building GraphQL APIs.
  grpc:
    name: gRPC
    icon: webhook
    description: Specification for building gRPC APIs.
  wsdl:
    name: WSDL
    icon: bubbles
    description: Specification for building SOAP APIs.

group_types:
  business_unit:
    name: Business Unit
    icon: building
    description: A division within the organization responsible for specific business functions.
  product_area:
    name: Product Area
    icon: box
    description: A specific area of focus within the product portfolio.
  team:
    name: Team
    icon: users-round
    description: A group of people working together on a project.

lifecycles:
  experimental:
    name: 'Experimental'
    icon: 'flask-conical'
    description: 'This component is experimental and should not be used in production.'
  production:
    name: 'Production'
    icon: 'badge-check'
    description: 'This component is stable and used in production.'
  deprecated:
    name: 'Deprecated'
    icon: 'archive'
    description: 'This component is deprecated and will be removed in the future.'

kinds:
  api:
    name: 'API'
    icon: 'waypoints'
  database:
    name: 'Database'
    icon: 'database'
  library:
    name: 'Library'
    icon: 'library'
  web:
    name: 'Web Service'
    icon: 'globe'
  worker:
    name: 'Worker'
    icon: 'cog'

environments:
  sandbox:
    id: 'sandbox'
    name: 'Sandbox'
    icon: 'codesandbox'
    description: 'For exploration and development of proof-of-concepts.'
  development:
    id: 'development'
    name: 'Development'
    icon: 'code'
    description: 'For local development and testing.'
  testing:
    id: 'testing'
    name: 'Testing'
    icon: 'test-tube-diagonal'
    description: 'Testing environment.'
  qa:
    id: 'qa'
    name: 'QA'
    icon: 'tablet-smartphone'
    description: 'Quality assurance environment.'
  staging:
    id: 'staging'
    name: 'Staging'
    icon: 'shield-alert'
    description: 'Pre-production environment for final validation.'
  production:
    id: 'production'
    name: 'Production'
    icon: 'cloud'
    description: 'Live environment serving end-users.'

platforms:
  aws:
    id: 'aws'
    name: 'Amazon Web Services'
    icon: 'boxicons:aws:logos'
    description: 'Deployed on Amazon Web Services.'
  aptible:
    id: 'aptible'
    name: 'Aptible'
    icon: 'cloud'
    description: 'Deployed on the Aptible PaaS.'

resources:
  bucket:
    name: 'Bucket'
    icon: 'box'
  database:
    name: 'Database'
    icon: 'database'
  queue:
    name: 'Queue'
    icon: 'rows-4'
